apiVersion: apps/v1
kind: Deployment
metadata:
  name: labnginx-deployment
  namespace: labnginx
  labels:
    app: nginx-app
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
        - name: nginx-app
          image: nginx:latest
          ports:
            - containerPort: 80
  selector:
    matchLabels:
      app: nginx-app
