# apiVersion: v1
# kind: Service
# metadata:
#   name: svc-nginx
#   namespace: labnginx
# spec:
#   type: LoadBalancer
#   ports:
#     - port: 80
#       nodePort: 30000
#   selector:
#     app: nginx-app
apiVersion: v1
kind: Service
metadata:
  name: svc-nginx
  namespace: labnginx
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30500
  selector:
    app: nginx-app
